name: Integration Tests

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  integration-tests:
    name: Run Integration Tests
    runs-on: ubuntu-latest
    
    services:
      mongodb:
        image: mongo:7
        ports:
          - 27017:27017
        options: >-
          --health-cmd "mongosh --eval 'db.runCommand({ ping: 1 })'"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'yarn'
      
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'
      
      - name: Install Backend Dependencies
        run: |
          cd backend
          pip install -r requirements.txt
      
      - name: Install Frontend Dependencies
        run: yarn install --frozen-lockfile
      
      - name: Start Backend Server
        run: |
          cd backend
          python server.py &
          sleep 5
        env:
          MONGO_URL: mongodb://localhost:27017/test_db
          PORT: 8001
      
      - name: Build Frontend
        run: |
          cd apps/web
          yarn build
        env:
          NEXT_PUBLIC_BACKEND_URL: http://localhost:8001
      
      - name: Run Integration Tests
        run: |
          cd apps/web
          yarn test:integration
        env:
          NEXT_PUBLIC_BACKEND_URL: http://localhost:8001
      
      - name: Upload Test Results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: integration-test-results
          path: |
            apps/web/test-results/
            backend/test-results/
