name: Snyk Security Scan

on:
  push:
    branches:
      - main
      - 'feature/**'
  pull_request:
    branches:
      - main
  schedule:
    # Run daily at 2 AM UTC
    - cron: '0 2 * * *'
  workflow_dispatch:

permissions:
  contents: read
  security-events: write
  actions: read

jobs:
  snyk-scan:
    name: Snyk Security Scan
    runs-on: ubuntu-latest
    
    strategy:
      fail-fast: false
      matrix:
        project:
          - name: 'Root Dependencies'
            path: '.'
          - name: 'Frontend (Web)'
            path: 'apps/web'
          - name: 'Backend (API)'
            path: 'apps/api'
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/node@master
        continue-on-error: true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --all-projects --severity-threshold=high --project-name="${{ matrix.project.name }}"
          command: test

      - name: Upload Snyk results to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: snyk.sarif

  snyk-monitor:
    name: Snyk Monitor
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Monitor project with Snyk
        uses: snyk/actions/node@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          command: monitor
          args: --all-projects

  snyk-docker:
    name: Snyk Docker Scan
    runs-on: ubuntu-latest
    if: github.event_name == 'push' || github.event_name == 'pull_request'
    
    strategy:
      fail-fast: false
      matrix:
        dockerfile:
          - name: 'Frontend Docker Image'
            path: 'apps/web/Dockerfile'
            context: 'apps/web'
          - name: 'Backend Docker Image'
            path: 'apps/api/Dockerfile'
            context: 'apps/api'
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: |
          docker build -t ${{ matrix.dockerfile.name }}:latest -f ${{ matrix.dockerfile.path }} ${{ matrix.dockerfile.context }}

      - name: Run Snyk to check Docker image for vulnerabilities
        uses: snyk/actions/docker@master
        continue-on-error: true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          image: ${{ matrix.dockerfile.name }}:latest
          args: --severity-threshold=high --file=${{ matrix.dockerfile.path }}

      - name: Upload Snyk Docker results to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: snyk.sarif
